AllCops:
  TargetRubyVersion: 3.1.0
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false
